### ISSUE TITLE
Add additional Data

### ISSUE THREAD

**Issue by waynegraham** [clirdlf/hidden_collections_registry#11]
Need to update the app with additional data from WizeHive system

**Comment by nkferraiolo** [comment]
I've shared a spreadsheet with you with WizeHive data for the 2015 grantees. We should discuss it together and find out if this spreadsheet would be sufficient or if I should make adjustments before you input it. Once we know we have the fields right, I can send you the data for the 2014 and 2016 grantees.

**Comment by waynegraham** [comment]
Things I don't see in this export:

- `hc_id`
- `formats` 
- `sizes` 
- `end_range`
- `size`
- `subject`

We at least need something for the `hc_id`. Is there an standard identifier for these records?

**Comment by nkferraiolo** [comment]
OK, I've added a couple of fields that may have the information we're looking for. I'll sent you an updated spreadsheet over WizeHive. 

hc_id: I've added two new fields called Submission ID and Page ID. Let me know if either of these seem consistent with what we have already. 

formats: I've added a new column called "Type of Materials", and another one called "Type of Materials: Other" which should have this information. 

sizes: I've added columns called "Amount of Materials" and "Unit of Measurement" that should have this information. Note that not all of these will be measured in terms of "boxes."

end_range: I believe this refers to the end range of dates. Unfortunately, this does not seem to map perfectly. My guess is that in the cataloging program, we had one field for the start of the date range and another field for the end of the date range. Whereas in the digitization program, we just have one field that asks for the full date range (start to finish).

size: I'm not sure what this second size field refers to. 

subject: I don't think that we asked for this with the DHC applicants. We may have even added this after the fact for CHC. If so, I'm not sure I'd want to continue with this field for the DHC recipients because it's subjective and I don't want to misrepresent the projects. We also haven't organized the search function for the registry in this way with the newer version.

**Comment by waynegraham** [comment]
I'm looking at the data you sent with multiple rows for the submissions (v3). What I noticed is that the difference between them is in the listing of stuff 

| Submission ID | Amount of Material | Unit of Measurement | Type of   Materials |
|--------------- | ------------------- | --------------------- |------------------- |
| 18602827        | 10                             | linear feet                   | manuscripts            |
| 18602827        | 3                               | items                          | other [list below]     |
| 18602827        | 22                             | volumes                     | volumes                   |
| 18602827        | 14                             | items                          | ephemera                |
| 18602827        | 159510                     | pages                         | manuscripts             |

How should this be handled? Right now the way the import works is that it finds a record and updates it (if it exists) based on the `submission id`. This particular instance would show 159,510 pages of manuscripts (because it's the last field), but not the other fields.

There are a few different ways I can see to handle this. 

- Ignore and just live with the fact that that you get the last value in the spreadsheet
- Develop logic that combines these fields and shoves them in to the amount fields 
- Create a new object that handles material types and counts

I need to do a little exploring to figure out which might be the best path forward, but do you have any thoughts on how you want this displayed?

**Comment by nkferraiolo** [comment]
Hmmm that's a good question. I wonder if it makes sense to have a new field for the digitization projects that handles differently than the cataloging projects. That way we could leave the cataloging data as is, while customizing the digitization data to meet our needs. Perhaps we could call this field "digitization deliverables," so that it accounts for the amount, unit, and type of material. You would obviously have a better sense as to how to approach this from a technical standpoint. From a display standpoint, we could do a table, similar to the one you've included here. Bullet points could also work, such as: 

Digitization Deliverables: 
- 10 linear feet of manuscripts
- 3 items of other [we'll need to pull from their description if they do this]
- 22 volumes of volumes [this will obviously need some manual editing]
- 14 items of ephemera
- 159510 pages of manuscripts

It would be great if we could use the registry to help us track these deliverables internally. That's something to consider as we set up this section.

**Comment by waynegraham** [comment]
We can have different profiles for the different programs. It may be worth having a 10 minute conversation about this and what we're trying to convey to users.

**Comment by nkferraiolo** [comment]
Hi Wayne, that would be a good idea. I'm free for a call until 12:30pm today: 650-465-1508. I'm also free all day tomorrow.

**Comment by nkferraiolo** [comment]
Hi Wayne, 

I've exported and cleaned up all of the missing registry data and written up my workflow so that other people can repeat this work for the 2017 cycle data and beyond. I sent you an email with the relevant spreadsheets, which I've copied below. The spreadsheets and the workflow files can also be found in the P:Drive under: Public/CLIR Programs/Hidden Collections/Registry/. Unfortunately, GitHub doesn't support excel files so I can't attach them here. 

Let me know if you have any questions! 

Nikki 



Hi Wayne,
 
I’ve attached the spreadsheets with the missing registry data:
 
1)       Registry Data 2014_Funded
2)       Registry Data 2014_Unfunded
3)       Registry Data 2015_All
4)       Registry Data 2016_Funded
5)       Registry Data 2016_Unfunded
 
I’ve also attached a document outlining my workflow for exporting this data, as well as some additional background on my thought process.
 
Some notes on the spreadsheets:
 
·         The 2014 datasets (the last year of the CHC program) do not have as many fields as the Digitizing Hidden Collections datasets. Any missing information can simply be left out of the registry. Several of the fields from this year also had somewhat different names than the Digitization ones we used as a model. I’ve gone ahead and changed them to match to save you the trouble of having to map it.
·         For most of the missing years, I’ve provided two spreadsheets: one for funded projects and one for unfunded projects. The 2015 data includes both the funded and unfunded projects on one spreadsheet. This is because of my crazy idea to have one master spreadsheet, which as you correctly predicted, wasn’t worth the effort. This was the first one I did and I’d prefer not to redo it if possible.
·         I’ve also added in a column at the beginning of each spreadsheet called “Funded?.” I’ve marked an X in the column for all funded projects. I’ve left those that were not funded blank.
·         WizeHive does not automatically include the year of the application cycle. In all of the reports, I manually replaced a column called “Folder” with once called “Year” and have added the correct year.
·         The order of the columns isn’t the same on all of the spreadsheets, but the names of each column should be the same
 
Let me know if you need any clarification or additional data. Thanks so much for prioritizing this crazy project. I’ll try to keep changes from here on out to a minimum.
 
Have a good night!
 
Nikki

**Comment by waynegraham** [comment]
When this is done, I'm going to update directions for adding this data directly to GitHub and not touching the P: drive...(see [wizehive_export](https://github.com/clirdlf/hidden_collections_registry/blob/master/doc/wizehive_export.md))

**Comment by nkferraiolo** [comment]
I've sent you an email breaking up the 2015 dataset into two spreadsheets--one for funded projects and one for unfunded projects. I believe you should now have the data for all years of the hidden collections program.
