### ISSUE TITLE
Files 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/hidden_collections_registry#4]
Is it possible to link the files to the project that they relate to, rather than having all of them appear at the top of each unique registry entry? We'll also probably want to add a field for file descriptions (these can be pulled from the grantee's reports moving forward.)

**Comment by waynegraham** [comment]
This current view was just a proof-of-concept to see if I could pull the data from S3. Only documents associated with a given grant will be displayed on the page.

**Comment by waynegraham** [comment]
I'm taking a closer look at this and there's not a way to automate matching the documents with the projects because of the naming conventions used. Unfortunately there will need to be some manual intervention to manually rename the files to associate them with the proper record. 

Is there any matching of the documents with the HC registry IDs in Plone? There were a lot of inconsistencies in the institution field (and how they were named). 

One way to handle this would be for each report to get it's own directory based on it's ID in the database. For instance, Sacred, Secular, and Sewn with Soul: Discovering Alabama's Folk Culture (http://staging.registry.hiddencollections.clir.org/projects/1018) would be in a directory `1018`). Any associated files that need to go in there would show up in this folder and be auto-displayed on the page.

**Comment by nkferraiolo** [comment]
Is it possible for the directory ID to be the same as the grant ID? That would be awesome, especially if we could figure out a way someday in the distant future to automatically pull documents from their report forms in WizeHive (and it’s successor platform). I could easily provide you with all of the grant numbers.

I think that the files situation isn’t the biggest priority and can wait until Adam’s replacement is hired. We don’t need them to have a functioning registry—these are more for our registry wish-list. Eventually we will want them because, as of now, we don’t have a way of sharing the models and tools that have come out of the programs. But these can wait until after August.

For now, we can just hide the files that are already in the system.

**Comment by waynegraham** [comment]
Looks like the `id` for each of the reports is the actual report id (from the spreadsheet), so this should be really straight forward. Should be able to drop files in there to display (including the thumbs).

**Comment by nkferraiolo** [comment]
Wow! Awesome! Let me know if there’s anything I can do to help out with this.

**Comment by waynegraham** [comment]
Are these by any chance organized like this on the P drive? Or do we have to wait for someone to sort that out?

**Comment by nkferraiolo** [comment]
I could have sworn I saw them on the P-Drive at some point but I can't find them for the life of me! This predated me and I think Christa would be the person most likely to know where the files are. Let me drop her a note and see if she has a sense of their current location.

**Comment by nkferraiolo** [comment]
OK I spoke with Christa and she thinks she has the files on her old computer. If not, we can download them and retitle or upload as needed. We'll likely assign this to the program assistant, but I'm willing to help with this too.

**Comment by waynegraham** [comment]
I'm relabeling this as a TODO as I believe we're pushing this down the line until the new person is hired to sort out additional documents.

**Comment by waynegraham** [comment]
A "solution" for this was documented in 7ad6953482426d0b652a63ce0808b968d9cbeda0. If there are additional requirements, please open a new ticket.
