### ISSUE TITLE
Export data feature

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/hidden_collections_registry#45]
Is there any way external users of the registry can export the registry data? Amy asked about this. we should chat with her about whether this is necessary and what would be a realistic timeline for this functionality. I don't think it's urgent.

**Comment by nkferraiolo** [comment]
I don't think this is urgent. Can probably be pushed back to launch of new website or even later into 2018 (if we determine it is necessary at all).

**Comment by waynegraham** [comment]
Is this something that was promised? I'd like to know more about the use case for this, and a how big of a priority this is. I'm not sure the effort to do this would justify adding this feature for the amount of use, particularly since the source files are all already in GitHub.

**Comment by nkferraiolo** [comment]
We did not promise this. I think Amy will likely be convinced by the argument that the files are in github. I'll let you know if she has a reason to push for it.

**Comment by waynegraham** [comment]
@christawilliford Is an export data feature really necessary? All the data is currently in GitHub.

**Comment by christawilliford** [comment]
I think pointing people to files on GitHub will be sufficient once we have a complete set of files there. However, if there were a way to combine the data into one master file and name it something more diplomatic than Funded/Unfunded, that would be better. I have been trying to talk up the value of making data available to other funders and so the value of this functionality falls more on how it would help us persuade others to make their data available to us, rather than having any real understanding about how others want to use our data. So for that reason, it can't be seen as top priority.

**Comment by waynegraham** [comment]
I just added a quick data API layer to enable this. Data can be pulled at http://registry.clir.org/projects.json.

All of the data can be downloaded, as well as searches (e.g. http://registry.clir.org/projects.json?search=Natural%20History). This allows application developers access to the information, as well as in the CSV format of the individual years in github.

Does this satisfy this request?

**Comment by waynegraham** [comment]
I haven't heard any more on this, so I'm closing  (closed in e7a9b6b44deab0da062d8476b5f4c5dc63c4831c).

**Comment by christawilliford** [comment]
Yes affirming here that the api should serve the need. Thank you for going the extra mile on this. We'll need to think through a good way to document and promote this once we have our data issues resolved.
